version: '1.24.1'
services:
    flask:
        build: ./flask
        ports:
            - "5000:5000"
        expose:
            - "5000"
    nginx:
        build: ./nginx
        links:
            - flask
        ports: 
            - "8088:8088"
            - "80:80"
            - "443:443"
        restart: always