# LOCALHOST
# HOSTNAME = '127.0.0.1'
# PORT = '3306'
# DATABASE = 'DoctorJoe'
# USERNAME = 'root'
# PASSWORD = '04081350'

# WEIXIANG DEV SEVER
HOSTNAME = 'localhost'
PORT = '3306'
DATABASE = 'doctorjoe'
USERNAME = 'root'
PASSWORD = 'ca$hc0w'

# JOE DEV SERVER
# HOSTNAME = '10.117.43.79'
# PORT = '3306'
# DATABASE = 'doctorjoe'
# USERNAME = 'joe'
# PASSWORD = 'ca$hc0w'


DB_URI =  'mysql+pymysql://{}:{}@{}:{}/{}' \
          '?charset=utf8mb4'.format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False

SQLALCHEMY_POOL_SIZE=20
SQLALCHEMY_POOL_TIMEOUT=300

# mysql+mysqldb://root:04081350@127.0.0.1:3306/DoctorJoe